/**
 * Vercel Blob Storage Provider
 *
 * Implements storage using Vercel Blob (built-in Vercel storage)
 * Simple key-value storage with automatic CDN distribution
 *
 * TODO: Implement when Vercel Blob storage is needed
 * Required setup:
 * 1. npm install @vercel/blob
 * 2. Enable Vercel Blob in project settings
 * 3. Set environment variable: BLOB_READ_WRITE_TOKEN (auto-generated by Vercel)
 */

import { StorageProvider } from './StorageProvider.js';

export class VercelBlobProvider extends StorageProvider {
  constructor(config) {
    super(config);

    // Validate required config
    if (!config.token) {
      throw new Error('Vercel Blob token is required');
    }

    this.token = config.token;

    // TODO: Initialize Vercel Blob client
    // Note: Vercel Blob uses edge runtime, different from traditional storage
  }

  async getJson(path) {
    // TODO: Implement Vercel Blob get → parse JSON
    // const blob = await get(path, { token: this.token });
    // const text = await blob.text();
    // return { data: JSON.parse(text), sha: blob.uploadedAt };
    throw new Error('VercelBlobProvider not yet implemented. Use GitHubProvider.');
  }

  async saveJson(path, data, message, sha = null) {
    // TODO: Implement Vercel Blob put with JSON content
    // const blob = await put(path, JSON.stringify(data, null, 2), {
    //   access: 'public',
    //   token: this.token,
    //   contentType: 'application/json',
    // });
    // return { success: true, sha: blob.uploadedAt };
    throw new Error('VercelBlobProvider not yet implemented. Use GitHubProvider.');
  }

  async deleteFile(path, sha, message) {
    // TODO: Implement Vercel Blob del
    // await del(path, { token: this.token });
    // return { success: true };
    throw new Error('VercelBlobProvider not yet implemented. Use GitHubProvider.');
  }

  async listDirectory(path) {
    // TODO: Implement Vercel Blob list with prefix
    // const { blobs } = await list({ prefix: path, token: this.token });
    // return blobs.map(b => ({ name: b.pathname, path: b.pathname }));
    throw new Error('VercelBlobProvider not yet implemented. Use GitHubProvider.');
  }

  async uploadBinary(path, base64Content, message) {
    // TODO: Implement Vercel Blob put with binary content
    // const buffer = Buffer.from(base64Content, 'base64');
    // const blob = await put(path, buffer, { token: this.token });
    // return { success: true, sha: blob.uploadedAt };
    throw new Error('VercelBlobProvider not yet implemented. Use GitHubProvider.');
  }

  async getBinary(path) {
    // TODO: Implement Vercel Blob get → convert to base64
    // const blob = await get(path, { token: this.token });
    // const arrayBuffer = await blob.arrayBuffer();
    // return Buffer.from(arrayBuffer).toString('base64');
    throw new Error('VercelBlobProvider not yet implemented. Use GitHubProvider.');
  }
}

/**
 * Implementation Guide for VercelBlobProvider:
 *
 * 1. Install dependencies:
 *    npm install @vercel/blob
 *
 * 2. Import Vercel Blob functions:
 *    import { put, get, del, list } from '@vercel/blob';
 *
 * 3. Use in Vercel environment:
 *    - Token is auto-provided via BLOB_READ_WRITE_TOKEN env var
 *    - Works in Edge Runtime (super fast)
 *
 * 4. Implement getJson:
 *    const blob = await get(path, { token: this.token });
 *    if (!blob) return null;
 *    const text = await blob.text();
 *    return { data: JSON.parse(text), sha: blob.uploadedAt };
 *
 * 5. Implement saveJson:
 *    const blob = await put(path, JSON.stringify(data, null, 2), {
 *      access: 'public',
 *      token: this.token,
 *      contentType: 'application/json',
 *    });
 *    return { success: true, sha: blob.uploadedAt };
 *
 * 6. Benefits:
 *    - Automatic CDN distribution (fast worldwide)
 *    - Built into Vercel (no external service setup)
 *    - Pay-as-you-go pricing (very cheap for small apps)
 *
 * 7. Limitations:
 *    - No version control (unlike GitHub)
 *    - Simpler than S3 (which is good for most cases)
 */
